# p4unknown:IgnoreThisAutogeneratedFile
#
# File: DbEnum.tcl
#
# Description: Enum constants for database objects
#
# NOTE: This file is automatically generated.  DO NOT EDIT
#

#
# Enumerated type: ABChannel
#

namespace eval ABChannel {
    variable A 2
    variable B 3
    variable None 1
}

#
# Enumerated type: Action
#

namespace eval Action {
    variable Record 1
}

#
# Enumerated type: ActiveUIMode
#

namespace eval ActiveUIMode {
    variable ClassicUI 0
    variable FlashUI 1
}

#
# Enumerated type: AdContentImageBehavior
#

namespace eval AdContentImageBehavior {
    variable ActionableEvent 4
    variable EventSolo 2
    variable Sequence 1
}

#
# Enumerated type: AdContentUsage
#

namespace eval AdContentUsage {
    variable Billboard 17
    variable ClipIcon 10
    variable ClipInterstitalIn 15
    variable ClipInterstitalOut 16
    variable IPreviewIcon 12
    variable ShowcaseIcon 11
    variable ShowcaseInterstitalIn 13
    variable ShowcaseInterstitalOut 14
    variable Unknown 0
}

#
# Enumerated type: Advisory
#

namespace eval Advisory {
    variable AdultSituations 10
    variable BriefNudity 4
    variable GraphicLanguage 2
    variable GraphicViolence 5
    variable Language 1
    variable MildViolence 7
    variable Nudity 3
    variable Rape 9
    variable StrongSexualContent 8
    variable Violence 6
}

#
# Enumerated type: AllNightTest
#

namespace eval AllNightTest {
    variable Mode 5
    variable NoTest 1
    variable NumFiles 3
    variable Pop800 4
    variable ShortLong 2
}

#
# Enumerated type: AspectCorrection
#

namespace eval AspectCorrection {
    variable Full 1
    variable Panel 2
    variable WideZoom 4
    variable Zoom 3
}

#
# Enumerated type: AspectRatio
#

namespace eval AspectRatio {
    variable Smart_4_3 3
    variable Standard_4_3 1
    variable Wide_16_9 2
}

#
# Enumerated type: AttributeArity
#

namespace eval AttributeArity {
    variable Multi 3
    variable Optional 1
    variable Single 2
}

#
# Enumerated type: AttributeLevel
#

namespace eval AttributeLevel {
    variable Base 1
    variable Derived 2
}

#
# Enumerated type: AttributeType
#

namespace eval AttributeType {
    variable File 3
    variable Int 0
    variable Object 2
    variable String 1
}

#
# Enumerated type: AudioDrc
#

namespace eval AudioDrc {
    variable Off 0
    variable On 1
    variable RFOutput 2
}

#
# Enumerated type: AudioInput
#

namespace eval AudioInput {
    variable DolbyDigital 1
    variable Mpeg2 2
}

#
# Enumerated type: AudioLanguage
#

namespace eval AudioLanguage {
    variable Chinese 3
    variable ChineseCantonese 7959909
    variable ChineseMandarin 6516078
    variable English 1
    variable French 4
    variable German 5
    variable Hindi 6842734
    variable Italian 6
    variable Japanese 7
    variable Korean 8
    variable Maori 7168367
    variable Spanish 2
}

#
# Enumerated type: AudioMode
#

namespace eval AudioMode {
    variable Elementary 1
    variable PesTriple 2
}

#
# Enumerated type: AudioOutput
#

namespace eval AudioOutput {
    variable DolbyDigital 1
    variable Pcm 2
}

#
# Enumerated type: AudioSource
#

namespace eval AudioSource {
    variable Main 1
    variable Mono 3
    variable SAP 2
}

#
# Enumerated type: AuthTollFreeStates
#

namespace eval AuthTollFreeStates {
    variable Authorized 3
    variable Temporary 2
    variable Unauthorized 0
    variable Upgrade 1
}

#
# Enumerated type: AutoDetect
#

namespace eval AutoDetect {
    variable DaylightSavings 2
    variable None 0
    variable TimeZone 1
    variable TimeZoneAndDaylightSavings 3
}

#
# Enumerated type: AvalancheDataFormat
#

namespace eval AvalancheDataFormat {
    variable Blizzard 0
    variable BlizzardModified 2
    variable DtvSwUpdate 4
    variable Files 3
    variable PlanY 1
}

#
# Enumerated type: AvalancheFileType
#

namespace eval AvalancheFileType {
    variable BdfcpTornado 6
    variable Directory 0
    variable FeatureAuthorization 7
    variable GeneralDvrData 8
    variable Runme 2
    variable SkeletonSlice 5
    variable Slice 1
    variable Snowball 4
    variable SoftwareDownload 9
    variable Streamfile 3
}

#
# Enumerated type: AvalancheIceboxType
#

namespace eval AvalancheIceboxType {
    variable DirecTvDataFileObject 5
    variable Ext2File 2
    variable MfsStreamFile 3
    variable Phone 1
    variable RecordingObject 4
}

#
# Enumerated type: AvalancheLastStatus
#

namespace eval AvalancheLastStatus {
    variable CaptureAborted 4
    variable CaptureComplete 2
    variable CaptureFailed 3
    variable CaptureInProgress 1
    variable PostProcessFailed 7
    variable PostProcessInProgress 5
    variable PostProcessSuccess 6
    variable Unknown 0
}

#
# Enumerated type: Axis
#

namespace eval Axis {
    variable Country 131072
    variable Hardware -2147287040
    variable Language 65536
    variable Manufacturer -2147221504
}

#
# Enumerated type: AxisCountry
#

namespace eval AxisCountry {
    variable AT 131078
    variable AU 131077
    variable Any 135167
    variable BE 131079
    variable BR 131080
    variable CA 131081
    variable CH 131082
    variable CL 131083
    variable CN 131084
    variable CZ 131085
    variable DE 131075
    variable DK 131086
    variable FR 131087
    variable GB 131089
    variable GR 131088
    variable HU 131090
    variable IL 131091
    variable IN 131092
    variable IT 131093
    variable JP 131094
    variable MX 131076
    variable NL 131095
    variable NO 131096
    variable PL 131097
    variable PT 131098
    variable RO 131099
    variable RU 131100
    variable SE 131101
    variable SG 131102
    variable SK 131103
    variable UK 131074
    variable US 131073
    variable ZA 131104
}

#
# Enumerated type: AxisHardware
#

namespace eval AxisHardware {
    variable Any -2147282945
    variable CablecardAtsc -2147287031
    variable CablecardAtsc2 -2147287029
    variable CablecardAtsc3 -2147287027
    variable Combo -2147287038
    variable Combo3Chip -2147287036
    variable DirectvA3 -2147287026
    variable DirectvAtsc -2147287032
    variable DvbtPal -2147287028
    variable DvdRom -2147287035
    variable DvdRw -2147287034
    variable Neutron -2147287025
    variable NeutronXl -2147287024
    variable StandAsym2Tuner -2147287030
    variable Standalone -2147287039
    variable Standalone2 -2147287033
    variable Standalone3Chip -2147287037
}

#
# Enumerated type: AxisLanguage
#

namespace eval AxisLanguage {
    variable Any 69631
    variable De 65538
    variable En 65537
    variable Es 65539
    variable csCZ 65540
    variable csSK 65541
    variable daDK 65542
    variable deAT 65544
    variable deBE 65546
    variable deCH 65545
    variable deDE 65543
    variable elGR 65547
    variable enAU 65549
    variable enCA 65550
    variable enGB 65551
    variable enIE 65552
    variable enSG 65553
    variable enUS 65548
    variable enZA 65554
    variable esCL 65555
    variable esES 65557
    variable esMX 65556
    variable frBE 65561
    variable frCA 65559
    variable frCH 65560
    variable frFR 65558
    variable huHU 65562
    variable itIT 65563
    variable jaJP 65564
    variable msSG 65565
    variable nlBE 65567
    variable nlNL 65566
    variable nnNO 65568
    variable plPL 65569
    variable ptBR 65571
    variable ptPT 65570
    variable roRO 65572
    variable ruRU 65573
    variable skSK 65574
    variable svSE 65575
    variable taSG 65576
    variable trTR 65577
    variable zhCN 65578
    variable zhSG 65579
}

#
# Enumerated type: AxisManufacturer
#

namespace eval AxisManufacturer {
    variable Any -2147217409
    variable Att -2147221497
    variable Directv -2147221492
    variable Hns -2147221500
    variable Humax -2147221493
    variable Philips -2147221503
    variable Pioneer -2147221495
    variable Rca -2147221499
    variable Samsung -2147221496
    variable Sony -2147221502
    variable Thomson -2147221501
    variable Tivo -2147221498
    variable Toshiba -2147221494
}

#
# Enumerated type: CableType
#

namespace eval CableType {
    variable HRC 2
    variable IRC 1
    variable STD 3
}

#
# Enumerated type: CablecardType
#

namespace eval CablecardType {
    variable Empty 0
    variable Mcard 2
    variable Scard 1
}

#
# Enumerated type: CallHint
#

namespace eval CallHint {
    variable None 0
    variable TicketRequest 1
}

#
# Enumerated type: CancelReason
#

namespace eval CancelReason {
    variable AssetParsingError 65
    variable CancelledPurchase 42
    variable CaptureRequestExpired 30
    variable ChannelLineupChanged 13
    variable ChannelNotAvailable 70
    variable ConvertedLiveCache 21
    variable CopyProtected 47
    variable CopyProtectedWatchTimer 48
    variable DemoMode 8
    variable EamForceTune 61
    variable Expired 6
    variable ExplicitlyDeleted 12
    variable ExplicitlyDeletedFromToDo 24
    variable ExternalDiskRemoved 58
    variable FuzziesTurnedOff 17
    variable FuzzyStoppedEarly 18
    variable GotBetterSuggestion 7
    variable HttpFileNotFound 50
    variable HttpIncorrectOffset 73
    variable HttpInvalidRequest 71
    variable HttpNotAuthorized 49
    variable HttpSchemeUnsupported 72
    variable InternalError 4
    variable InvalidUrl 51
    variable LiveCacheOnlySuccessful 22
    variable MaxRecordingsExceeded 29
    variable MaxRecordingsNowShowing 33
    variable MpegChecksumError 54
    variable NegativelyPadded 46
    variable NetworkSchedulerError 67
    variable NoChannelForStation 39
    variable NoPurchaseHistoryForRecording 41
    variable NoReRecord 27
    variable NoSignal 28
    variable NoSignalTunerOne 31
    variable NoSignalTunerTwo 32
    variable NotAuthorized 26
    variable NotFirstRun 62
    variable PodFirmwareUpgrade 60
    variable PowerWasOff 5
    variable ProgramGuideChanged 14
    variable ProgramNotFoundOnSource 36
    variable ProgramSourceConflict 20
    variable ProgramSourceDiskConflict 23
    variable ProgramSourceExternalTunerConflict 59
    variable ProgramSourceModified 25
    variable ProgramSourceNotAllowedToRecord 38
    variable ProgramSourceRequiresCableCardConflict 63
    variable PurchasePriceIncrease 43
    variable RecordDifferentShowing 2
    variable RecorderEmergency 15
    variable ShowingCopyProtected 40
    variable SourceCouldNotBeContacted 37
    variable SourceNotFound 35
    variable StayOnLiveTv 3
    variable SubscriptionNotFound 64
    variable SwitchToLiveTv 1
    variable TransferDisallowed 66
    variable TransferError 52
    variable TransferStreamTypeUnsupported 57
    variable TransferTooBig 55
    variable TransferTooSlow 56
    variable TuningAdapterFirmwareUpgrade 68
    variable TuningAdapterUnplugged 69
    variable UnableToPrice 45
    variable UnableToRepurchase 44
    variable UnexpectedConflict 9
    variable Unknown 19
    variable UserCancelledSeasonPass 16
    variable UserRequestedRecording 10
    variable UserRequestedSeasonPass 11
    variable UserStoppedTransfer 53
    variable VideoMgrDeniedTuner 34
}

#
# Enumerated type: CaptureRequestCreator
#

namespace eval CaptureRequestCreator {
    variable Client 2
    variable Service 1
}

#
# Enumerated type: CaptureRequestState
#

namespace eval CaptureRequestState {
    variable Cancelled 2
    variable Processed 1
    variable Unprocessed 0
    variable UnprocessedNoChannel 3
    variable UnprocessedNoPGD 4
}

#
# Enumerated type: CgmsABit
#

namespace eval CgmsABit {
    variable CopyFreely 0
    variable CopyNever 3
    variable CopyNoMore 1
    variable CopyOnce 2
}

#
# Enumerated type: ChannelHolderType
#

namespace eval ChannelHolderType {
    variable CableCard 0
    variable DvbLastScan 2
    variable TuningResolver 1
}

#
# Enumerated type: ClipPlayListFeatureId
#

namespace eval ClipPlayListFeatureId {
    variable ClipInShowcases 0
}

#
# Enumerated type: ClosedCaptioningAnalogService
#

namespace eval ClosedCaptioningAnalogService {
    variable Cc1 1
    variable Cc2 2
    variable Cc3 3
    variable Cc4 4
    variable Off 0
    variable Text1 5
    variable Text2 6
    variable Text3 7
    variable Text4 8
    variable Xds 9
}

#
# Enumerated type: ClosedCaptioningColor
#

namespace eval ClosedCaptioningColor {
    variable Black 2
    variable Blue 5
    variable Cyan 8
    variable Default 0
    variable Green 4
    variable Magenta 7
    variable Red 3
    variable White 1
    variable Yellow 6
}

#
# Enumerated type: ClosedCaptioningDigitalService
#

namespace eval ClosedCaptioningDigitalService {
    variable Dtvcc1 1
    variable Dtvcc2 2
    variable Dtvcc3 3
    variable Dtvcc4 4
    variable Dtvcc5 5
    variable Dtvcc6 6
    variable Off 0
}

#
# Enumerated type: ClosedCaptioningFont
#

namespace eval ClosedCaptioningFont {
    variable Casual 6
    variable Cursive 7
    variable Default 0
    variable MonospaceSansSerif 4
    variable MonospaceSerif 2
    variable ProportionalSansSerif 5
    variable ProportionalSerif 3
    variable SmallCaps 8
    variable System 1
}

#
# Enumerated type: ClosedCaptioningLanguage
#

namespace eval ClosedCaptioningLanguage {
    variable ChineseCantonese 7959909
    variable ChineseMandarin 6516078
    variable English 6647399
    variable French 6713957
    variable German 6776178
    variable Hindi 6842734
    variable Italian 6911073
    variable Japanese 6975598
    variable Korean 7040882
    variable Maori 7168367
    variable Spanish 7565409
}

#
# Enumerated type: ClosedCaptioningTextSize
#

namespace eval ClosedCaptioningTextSize {
    variable Default 0
    variable Large 3
    variable Small 1
    variable Standard 2
}

#
# Enumerated type: ClosedCaptioningType
#

namespace eval ClosedCaptioningType {
    variable Cc1 1
    variable Cc2 2
    variable Cc3 3
    variable Cc4 4
    variable Off 0
    variable Text1 5
    variable Text2 6
    variable Text3 7
    variable Text4 8
    variable Xds 9
}

#
# Enumerated type: Color
#

namespace eval Color {
    variable Black 0
    variable Gray 6250335
}

#
# Enumerated type: ColorCode
#

namespace eval ColorCode {
    variable Bw 1
    variable Color 4
    variable ColorAndBw 2
    variable Colorized 3
}

#
# Enumerated type: Connector
#

namespace eval Connector {
    variable CompositeIn 3
    variable CompositeIn2 9
    variable CompositeOut 4
    variable DvIn 11
    variable RfIn 1
    variable RfIn2 12
    variable RfOut 2
    variable ScartIn 7
    variable ScartOut 8
    variable SvideoIn 5
    variable SvideoIn2 10
    variable SvideoOut 6
    variable Unknown 0
}

#
# Enumerated type: ContentType
#

namespace eval ContentType {
    variable Blizzard 8
    variable DemoMode 2
    variable FactoryDefault 6
    variable LiveCache 3
    variable Normal 1
    variable PlanY 7
    variable ReplaceableBg 9
    variable TivoClip 4
    variable WatchButDontRecord 5
}

#
# Enumerated type: Country
#

namespace eval Country {
    variable AU 3
    variable CA 4
    variable GB 5
    variable MX 2
    variable NZ 6
    variable US 1
}

#
# Enumerated type: CountryCode
#

namespace eval CountryCode {
    variable CN 2
    variable HK 4
    variable MO 6
    variable SG 5
    variable TW 3
    variable US 1
    variable Unknown 0
}

#
# Enumerated type: CrDiskBehavior
#

namespace eval CrDiskBehavior {
    variable Data 8
    variable Fuzzy 10
    variable KeepForever 2
    variable TivoClips 9
    variable UserRequested 5
}

#
# Enumerated type: CrPresentationBehavior
#

namespace eval CrPresentationBehavior {
    variable AstroSeasonPass 9
    variable AstroSingleExplicit 10
    variable CaptureRequestFuzzy 7
    variable Invisible 8
    variable SeasonPass 2
    variable SingleExplicit 1
    variable TivoClips 5
    variable Wishlist 3
}

#
# Enumerated type: CrProgramGuideBehavior
#

namespace eval CrProgramGuideBehavior {
    variable SeasonPass 2
    variable Service 5
    variable SingleExplicit 1
}

#
# Enumerated type: CrTunerBehavior
#

namespace eval CrTunerBehavior {
    variable DataBlizzard 9
    variable DataPlanY 5
    variable Fuzzy 7
    variable LowSingleExplicit 14
    variable SeasonPass 2
    variable SingleExplicit 1
    variable TivoClips 6
}

#
# Enumerated type: DBSRemoteMethod
#

namespace eval DBSRemoteMethod {
    variable IR 2
    variable SerialCable 4
    variable SerialDirecTvApg 3
    variable SerialDirecTvApgAlt 5
    variable SerialDirecTvMpg 1
    variable Unknown 0
}

#
# Enumerated type: DataFileDestination
#

namespace eval DataFileDestination {
    variable Ext2File 3
    variable MfsDb 2
    variable MfsStream 1
    variable Recording 4
    variable Unknown 0
}

#
# Enumerated type: DataFileStatus
#

namespace eval DataFileStatus {
    variable DownloadFailed 100
    variable FECCompleted 3
    variable FECFailed 101
    variable FECing 2
    variable PostProcessed 5
    variable PostProcessing 4
    variable PostProcessingFailed 102
    variable ReferToRecording 1
    variable Unknown 0
}

#
# Enumerated type: DaylightSavingsPolicy
#

namespace eval DaylightSavingsPolicy {
    variable No 1
    variable Yes 2
}

#
# Enumerated type: DemoModeType
#

namespace eval DemoModeType {
    variable DvdDemo 2
    variable ShowRoomDemo 3
    variable SimpleVideoDemo 1
    variable Unset 0
}

#
# Enumerated type: DeviceType
#

namespace eval DeviceType {
    variable ATSCBox 6
    variable Audio 5
    variable CableBox 3
    variable DSS 2
    variable TV 4
    variable Unknown 0
    variable VCR 1
}

#
# Enumerated type: DialMethod
#

namespace eval DialMethod {
    variable Pulse 1
    variable Tone 0
}

#
# Enumerated type: DigitDelay
#

namespace eval DigitDelay {
    variable Fast 4
    variable Medium 3
    variable Slow 2
    variable Unknown 0
    variable VerySlow 1
}

#
# Enumerated type: DiskBehavior
#

namespace eval DiskBehavior {
    variable Cds 18
    variable DataBlizzard 15
    variable DataDtvDfb 17
    variable DataDtvSwUpdate 16
    variable DataPlanY 8
    variable DemoModeOBSOLETE 11
    variable Fuzzy 10
    variable IndefiniteLength 14
    variable KeepLonger 4
    variable LiveCache 12
    variable Network 19
    variable NeverShortenSP 3
    variable NeverShortenSingle 2
    variable PayPerView 1
    variable ReplaceableBgOBSOLETE 13
    variable SeasonPassOBSOLETE 6
    variable SpeculativePayPerView 20
    variable TivoClipsOBSOLETE 9
    variable UserRequested 5
    variable WatchOnly 7
}

#
# Enumerated type: DiskConfigurationId
#

namespace eval DiskConfigurationId {
    variable 14Hour 10
    variable 20Hour 11
    variable 30HourDualCX 13
    variable 30HourDualEX 12
    variable 30HourDualLCTCombo 17
    variable 30HourLCT30Combo 14
    variable 30HourLCT30Stand 15
    variable 30HourLCT40Combo 16
    variable 60Hour 18
    variable TestConfig0 0
    variable TestConfig1 1
    variable TestConfig2 2
    variable TestConfig3 3
    variable TestConfig4 4
    variable TestConfig5 5
    variable TestConfig6 6
    variable TestConfig7 7
    variable TestConfig8 8
    variable TestConfig9 9
}

#
# Enumerated type: DiskPartitionId
#

namespace eval DiskPartitionId {
    variable ReplaceableBG 12
    variable SpeculativePPV 14
    variable TestPartition0 0
    variable TestPartition1 1
    variable TestPartition2 2
    variable TestPartition3 3
    variable TestPartition4 4
    variable TestPartition5 5
    variable TivoClips 11
    variable TmpStorage 13
    variable User 10
}

#
# Enumerated type: DisplayFormat
#

namespace eval DisplayFormat {
    variable 1080i 4
    variable 1080i50 128
    variable 1080p24 256
    variable 1080p25 2048
    variable 1080p30 512
    variable 1080p50 4096
    variable 1080p60 1024
    variable 480i 1
    variable 480p 2
    variable 576i 16
    variable 576p 32
    variable 720p 8
    variable 720p50 64
    variable None 0
    variable Obsolete 3
}

#
# Enumerated type: DisplayFormatMode
#

namespace eval DisplayFormatMode {
    variable Auto 8
    variable Fixed 1
    variable Hybrid 3
    variable Native 2
    variable NativePal 4
    variable None 0
}

#
# Enumerated type: Dolby
#

namespace eval Dolby {
    variable Dolby 1
    variable DolbyDigital 2
}

#
# Enumerated type: DvdDolbyDigital
#

namespace eval DvdDolbyDigital {
    variable DolbyDigital 1
    variable DolbyToPcm 2
}

#
# Enumerated type: DvdPcm
#

namespace eval DvdPcm {
    variable 96 2
    variable Convert96To48 1
}

#
# Enumerated type: DvdPermanentSubtitles
#

namespace eval DvdPermanentSubtitles {
    variable AudioLanguage 2
    variable SubtitleLanguage 1
}

#
# Enumerated type: DvdProgressiveOutput
#

namespace eval DvdProgressiveOutput {
    variable Interlaced 1
    variable Progressive 2
    variable ProgressiveShrink 3
}

#
# Enumerated type: DvdSubtitleDisplay
#

namespace eval DvdSubtitleDisplay {
    variable Assist 3
    variable Off 2
    variable On 1
}

#
# Enumerated type: DvdWideScreenFormat
#

namespace eval DvdWideScreenFormat {
    variable Letterbox 1
    variable PanAndScan 2
}

#
# Enumerated type: EncryptionKeyType
#

namespace eval EncryptionKeyType {
    variable Bare 1
    variable WrappedTivo 2
}

#
# Enumerated type: EpgIdType
#

namespace eval EpgIdType {
    variable HWW_AU 2
    variable TMS 1
    variable Unknown 0
}

#
# Enumerated type: ExpirationPolicy
#

namespace eval ExpirationPolicy {
    variable DataGroupListControlled 1
    variable ExpirationControlled 2
    variable Never 0
}

#
# Enumerated type: ExtendedFormatStringType
#

namespace eval ExtendedFormatStringType {
    variable PlainText 1
    variable Tvml 2
}

#
# Enumerated type: FirmwareDeviceType
#

namespace eval FirmwareDeviceType {
    variable dvd 1
    variable unknown 0
}

#
# Enumerated type: FirmwareVendorId
#

namespace eval FirmwareVendorId {
    variable hp 6
    variable iomega 5
    variable nec 2
    variable samsung 4
    variable takara 1
    variable teac 3
    variable unknown 0
}

#
# Enumerated type: FolderingRules
#

namespace eval FolderingRules {
    variable SeriesAndSubscription 3
    variable SeriesOnly 1
    variable SubscriptionOnly 2
}

#
# Enumerated type: FontFormat
#

namespace eval FontFormat {
    variable TrueType 1
}

#
# Enumerated type: FrontPanelBacklightLevel
#

namespace eval FrontPanelBacklightLevel {
    variable Bright 100
    variable Dim 12
    variable Off 0
    variable Regular 40
}

#
# Enumerated type: FrontPanelDisplayLevel
#

namespace eval FrontPanelDisplayLevel {
    variable Bright 100
    variable Dim 40
    variable Off 0
    variable Regular 66
    variable Unknown -1
}

#
# Enumerated type: FrontPanelLightLevel
#

namespace eval FrontPanelLightLevel {
    variable FormatOff 30
    variable Off 0
    variable On 60
}

#
# Enumerated type: GcZapPolicy
#

namespace eval GcZapPolicy {
    variable FactoryReset 1
    variable Never 0
    variable ProgramGuide 2
}

#
# Enumerated type: GuideChannelList
#

namespace eval GuideChannelList {
    variable All 1
    variable Favorite 2
    variable Surf 3
    variable Unset 0
}

#
# Enumerated type: GuideStyle
#

namespace eval GuideStyle {
    variable GridGuide 2
    variable TivoGuide 1
    variable Unset 0
}

#
# Enumerated type: ImageFormat
#

namespace eval ImageFormat {
    variable Gif 1
    variable Jpg 3
    variable Png 2
}

#
# Enumerated type: IncentiveParticipation
#

namespace eval IncentiveParticipation {
    variable Neutral 3
    variable NonParticipating 2
    variable Participating 1
    variable Unset 0
}

#
# Enumerated type: InternetRecordingType
#

namespace eval InternetRecordingType {
    variable SeasonPass 1
    variable SeasonPassHigh 2
    variable SingleExplicit 3
    variable SingleExplicitAboveSP 4
    variable SingleExplicitBelowSP 5
}

#
# Enumerated type: Interstitial
#

namespace eval Interstitial {
    variable Fixed 4
    variable None 1
    variable Random 2
    variable Rotate 3
}

#
# Enumerated type: Language
#

namespace eval Language {
    variable enGB 2
    variable enUS 1
    variable esMX 3
    variable frFR 4
}

#
# Enumerated type: LeadGenMenuAction
#

namespace eval LeadGenMenuAction {
    variable Cancel 2
    variable Info 3
    variable Submit 1
    variable ToggleGroup 4
}

#
# Enumerated type: LetterboxColor
#

namespace eval LetterboxColor {
    variable Black 1
    variable Gray 2
    variable Unknown 0
}

#
# Enumerated type: LicenseAcquisitionDataFormat
#

namespace eval LicenseAcquisitionDataFormat {
    variable WmdrmHeader 1
}

#
# Enumerated type: LineupType
#

namespace eval LineupType {
    variable Broadcast 16
    variable CableALineupGroup 100
    variable CableBLineupGroup 101
    variable CableReadyABasic 73
    variable CableReadyAExtendedBasic 74
    variable CableReadyAGroup 98
    variable CableReadyAPayPerView 76
    variable CableReadyAPremium 75
    variable CableReadyBBasic 77
    variable CableReadyBExtendedBasic 78
    variable CableReadyBGroup 99
    variable CableReadyBPayPerView 80
    variable CableReadyBPremium 79
    variable CableReadyBasic 25
    variable CableReadyExtendedBasic 26
    variable CableReadyGroup 86
    variable CableReadyPayPerView 28
    variable CableReadyPremium 27
    variable CableReadySetsBasic 37
    variable CableReadySetsExtendedBasic 38
    variable CableReadySetsGroup 89
    variable CableReadySetsPayPerView 40
    variable CableReadySetsPremium 39
    variable DBSBasic 17
    variable DBSGroup 84
    variable DBSPackage 18
    variable DBSPayPerView 20
    variable DBSSingle 19
    variable DDeviceCableReadyBasic 33
    variable DDeviceCableReadyExtendedBasic 34
    variable DDeviceCableReadyGroup 88
    variable DDeviceCableReadyPayPerView 36
    variable DDeviceCableReadyPremium 35
    variable DigitalBasic 11
    variable DigitalExtendedBasic 12
    variable DigitalGroup 83
    variable DigitalPayPerView 14
    variable DigitalPremium 13
    variable DigitalRebuild 15
    variable DigitalRebuildBasic 29
    variable DigitalRebuildExtendedBasic 30
    variable DigitalRebuildGroup 87
    variable DigitalRebuildPayPerView 32
    variable DigitalRebuildPremium 31
    variable HamlinConverterBasic 41
    variable HamlinConverterExtendedBasic 42
    variable HamlinConverterGroup 90
    variable HamlinConverterPayPerView 44
    variable HamlinConverterPremium 43
    variable JerroldConverterBasic 49
    variable JerroldConverterExtendedBasic 50
    variable JerroldConverterGroup 92
    variable JerroldConverterPayPerView 52
    variable JerroldConverterPremium 51
    variable JerroldImpulseConverterBasic 45
    variable JerroldImpulseConverterExtendedBasic 46
    variable JerroldImpulseConverterGroup 91
    variable JerroldImpulseConverterPayPerView 48
    variable JerroldImpulseConverterPremium 47
    variable OakConverterBasic 57
    variable OakConverterExtendedBasic 58
    variable OakConverterGroup 94
    variable OakConverterPayPerView 60
    variable OakConverterPremium 59
    variable PioneerConverterBasic 53
    variable PioneerConverterExtendedBasic 54
    variable PioneerConverterGroup 93
    variable PioneerConverterPayPerView 56
    variable PioneerConverterPremium 55
    variable PrimaryBasic 1
    variable PrimaryExtendedBasic 2
    variable PrimaryGroup 81
    variable PrimaryPayPerView 4
    variable PrimaryPremium 3
    variable PrimaryRebuild 5
    variable RebuildBasic 21
    variable RebuildExtendedBasic 22
    variable RebuildGroup 85
    variable RebuildPayPerView 24
    variable RebuildPremium 23
    variable ScientificAtlantaConverterBasic 65
    variable ScientificAtlantaConverterExtendedBasic 66
    variable ScientificAtlantaConverterGroup 96
    variable ScientificAtlantaConverterPayPerView 68
    variable ScientificAtlantaConverterPremium 67
    variable SecondaryBasic 6
    variable SecondaryExtendedBasic 7
    variable SecondaryGroup 82
    variable SecondaryPayPerView 9
    variable SecondaryPremium 8
    variable SecondaryRebuild 10
    variable TocomConverterBasic 61
    variable TocomConverterExtendedBasic 62
    variable TocomConverterGroup 95
    variable TocomConverterPayPerView 64
    variable TocomConverterPremium 63
    variable Unknown 0
    variable ZenithConverterBasic 69
    variable ZenithConverterExtendedBasic 70
    variable ZenithConverterGroup 97
    variable ZenithConverterPayPerView 72
    variable ZenithConverterPremium 71
}

#
# Enumerated type: LinkTagIconType
#

namespace eval LinkTagIconType {
    variable IPreview 1
    variable MoreInfo 3
    variable None 0
    variable SmallIPreview 2
}

#
# Enumerated type: Live
#

namespace eval Live {
    variable Delay 1
    variable Live 3
    variable Tape 2
}

#
# Enumerated type: LiveCacheMode
#

namespace eval LiveCacheMode {
    variable ChannelHistory 2
    variable CurrentChannel 1
}

#
# Enumerated type: LocalMessageNumber
#

namespace eval LocalMessageNumber {
    variable Activate63 63
    variable ActivateCombo81 81
    variable CableCARDMismatch124 124
    variable CallInRequired58 58
    variable CallInSoonMsgCombo57 57
    variable ChannelChangingFollowUp120 120
    variable ChannelChangingNotSetUp119 119
    variable ChannelListIntro123 123
    variable ChoosePOPNum69 69
    variable Closed68 68
    variable CreditCardExpired126 126
    variable CryptoFailure51 51
    variable DVDProblem109 109
    variable ExpiredTicket100 100
    variable ExternalDriveDetected125 125
    variable FreeTrialExpiring94 94
    variable FreeTrialExpiringActNow95 95
    variable GreenScreen121 121
    variable HeadendNotFound50 50
    variable InternalError86 86
    variable InvalidPOPNum70 70
    variable LineupChange62 62
    variable LineupNotFound61 61
    variable LineupNotSetUp117 117
    variable LowPGDMsg59 59
    variable NetworkAdapterDetected88 88
    variable NetworkAutoenabled87 87
    variable NeverSetUp64 64
    variable NewPOPNums73 73
    variable NewPOPNumsTollFree74 74
    variable NewTuningResolver132 132
    variable NoPGDMessage60 60
    variable OnlineReqChanNotReceived108 108
    variable OnlineReqConflicts106 106
    variable OnlineReqNotScheduled105 105
    variable OnlineReqNotYetScheduled107 107
    variable OnlineReqScheduled103 103
    variable OnlineReqSomeScheduled104 104
    variable OptInNotification99 99
    variable OptNeutralNotification101 101
    variable OptOutNotification102 102
    variable OxygenCallInRequired90 90
    variable OxygenClosed98 98
    variable OxygenLowPGDMsg91 91
    variable OxygenNoPGDMsg92 92
    variable OxygenPastDueDowngradeService96 96
    variable POPDenyTollFree71 71
    variable POPUseTollFree72 72
    variable PastDue65 65
    variable PastDueDeactivate67 67
    variable ProviderNotSetUp115 115
    variable RemoteControlSetupIntro113 113
    variable RequestNewProvider116 116
    variable SeasonPassIntro110 110
    variable ShowcasesIntro112 112
    variable SuggestionsIntro122 122
    variable TuningResolverMissing131 131
    variable Unknown 0
    variable VideoHookupNotSetUp118 118
    variable WatchAndRecordIntro114 114
    variable WelcomeToFreeTrial93 93
    variable WirelessFirmwareUpdateRequired89 89
    variable WishListIntro111 111
}

#
# Enumerated type: LocalMessageType
#

namespace eval LocalMessageType {
    variable ActivateCombo 29
    variable BasicServiceCancelled 35
    variable ChoosePOPNum 7
    variable Closed 21
    variable CryptoFailure 25
    variable CryptoKeysCorrupted 26
    variable CryptoKeysMissing 27
    variable CryptoKeysOutdated 28
    variable Deactivate 3
    variable DemoLowPGD 23
    variable DemoNoConnect 22
    variable DemoNoPGD 24
    variable ExpiredTicket 37
    variable FreeTrialExpiring 31
    variable FreeTrialExpiringActNow 32
    variable FullServiceActivated 34
    variable InvalidPOPNum 8
    variable LowProgramGuide 5
    variable NeverSetUp 20
    variable NewPOPNums 9
    variable NewPOPNumsTollFree 10
    variable NoConnect 4
    variable NoConnectNowReqd 18
    variable NoConnectUrgent 17
    variable NoProgramGuide 19
    variable NotSetUp 14
    variable OptInNotification 36
    variable OptNeutralNotification 38
    variable OptOutNotification 39
    variable POPDenyTollFree 13
    variable POPUpgrade 11
    variable POPUseTollFree 12
    variable PastDue 15
    variable PastDueDeactivate 16
    variable PastDueDowngradeService 33
    variable PendingActivate 1
    variable PendingDeactivate 2
    variable ReallyLowProgramGuide 6
    variable WelcomeToFreeTrial 30
}

#
# Enumerated type: LogoSpace
#

namespace eval LogoSpace {
    variable DirecTV 2
    variable Tivo 1
    variable Troy 3
}

#
# Enumerated type: LoopSetVideoFormat
#

namespace eval LoopSetVideoFormat {
    variable Ac3Audio 2
    variable DvdVob 5
    variable MpegAudio 1
    variable MpegVideo 0
    variable MpegVideoAc3Audio 4
    variable MpegVideoMpegAudio 3
}

#
# Enumerated type: MediaEncryptionKeyType
#

namespace eval MediaEncryptionKeyType {
    variable Aes128 3
    variable None 0
    variable TivoKey 2
    variable TivoKeyLegacy 1
}

#
# Enumerated type: MediaSigningKeyType
#

namespace eval MediaSigningKeyType {
    variable HmacSha1_128 1
    variable None 0
}

#
# Enumerated type: MenuItemArea
#

namespace eval MenuItemArea {
    variable BottomNowPlayingLocalFolders 12
    variable CachedActionsMoreOptions 13
    variable DeleteRecording1 11
    variable MessageBoardPmi 15
    variable NowPlayingLocalList1 24
    variable NowPlayingLocalList2 25
    variable NowPlayingLocalList3 26
    variable NowPlayingLocalList4 27
    variable Nowhere 2
    variable PauseMenu1 16
    variable PauseMenu2 17
    variable PauseMenu3 18
    variable PauseMenu4 19
    variable PauseMenu5 20
    variable PickProgramsToRecord 4
    variable PickProgramsToRecord2 8
    variable PickProgramsToRecord3 9
    variable PickProgramsToRecord4 14
    variable SearchByTitleDemo 5
    variable Showcases 21
    variable TivoCentral 1
    variable TivoCentral2 3
    variable TivoCentral3 6
    variable TivoCentral4 7
    variable TivoCentral5 10
    variable TivoCentral6 22
    variable TivoCentral7 23
}

#
# Enumerated type: MenuItemDisplayFormat
#

namespace eval MenuItemDisplayFormat {
    variable Double 2
    variable Single 1
}

#
# Enumerated type: MenuItemFilterSource
#

namespace eval MenuItemFilterSource {
    variable Unknown 0
    variable ViewedRecording 1
}

#
# Enumerated type: MenuItemType
#

namespace eval MenuItemType {
    variable Clip 2
    variable FindActions 3
    variable Hme 6
    variable Showcase 1
    variable ShowcaseGrid 5
    variable SpecialtyGuides 7
    variable VODClip 10
    variable VODMenu 9
    variable Video 4
    variable Wormhole 8
}

#
# Enumerated type: MessageDestination
#

namespace eval MessageDestination {
    variable MessageBoard 1
    variable PreTivoCentral 2
}

#
# Enumerated type: MessageLevel
#

namespace eval MessageLevel {
    variable Any -1
    variable CapDeactivated 113
    variable Closed 108
    variable Deactivated 110
    variable Evaluation 111
    variable FullServiceExpiredTicket 120
    variable Good 103
    variable Lifetime 105
    variable NeverSetUp 107
    variable New 101
    variable NotSetUp 102
    variable OxygenBecausePastDue 123
    variable OxygenCancelled 122
    variable OxygenExpiredTicket 121
    variable OxygenFreeTrial 118
    variable OxygenFreeTrialNotPermitted 119
    variable OxygenFreeTrialPermitted 117
    variable PastDue 106
    variable Stolen 109
    variable Storefront 112
    variable Test 104
    variable Unknown 0
}

#
# Enumerated type: MessagePriority
#

namespace eval MessagePriority {
    variable High 1
    variable Low 3
    variable Medium 2
}

#
# Enumerated type: MessageSrc
#

namespace eval MessageSrc {
    variable DtvCam 12
    variable InternetRecording 10
    variable NetworkSetup 11
    variable Prioritizer 4
    variable Recorder 6
    variable Scheduler 3
    variable Service 1
    variable ServiceIndiv 8
    variable Setup 5
    variable SwPublishing 9
    variable TCDGeneral 2
    variable Test 9999
    variable Tuner 7
}

#
# Enumerated type: ModemMode
#

namespace eval ModemMode {
    variable Unknown 0
    variable V34 2
    variable V90 1
}

#
# Enumerated type: Mpaa
#

namespace eval Mpaa {
    variable Ao 7
    variable Bbfc12 10
    variable Bbfc15 11
    variable Bbfc18 12
    variable BbfcU 9
    variable G 1
    variable Nc17 6
    variable Nr 8
    variable Pg 2
    variable Pg13 3
    variable R 4
    variable Unknown 0
    variable X 5
}

#
# Enumerated type: NetConfig80211AuthenticationType
#

namespace eval NetConfig80211AuthenticationType {
    variable None 1
    variable Open 3
    variable Shared 4
    variable Wep 2
    variable Wpa 5
    variable Wpa2 8
    variable Wpa2Eap 10
    variable Wpa2Psk 9
    variable WpaEap 7
    variable WpaPsk 6
}

#
# Enumerated type: NetConfig80211EncryptionType
#

namespace eval NetConfig80211EncryptionType {
    variable Aes 4
    variable None 1
    variable Tkip 3
    variable Wep 2
}

#
# Enumerated type: NetConfig80211KeyType
#

namespace eval NetConfig80211KeyType {
    variable None 1
    variable RawBytes 2
    variable TextAlgo1 9
    variable TextAlgo2 10
    variable TextAlgo3 11
    variable TextAlgo4 12
    variable TextAscii128Bit 7
    variable TextAscii64Bit 6
    variable TextAuto 3
    variable TextAuto128Bit 5
    variable TextAuto64Bit 4
    variable TextHexString 8
    variable TextWpaString 13
}

#
# Enumerated type: NetConfigNetworkMedium
#

namespace eval NetConfigNetworkMedium {
    variable HomePna 9
    variable Iee1394 8
    variable Pots 3
    variable PowerLine 10
    variable Serial 2
    variable Unknown 1
    variable Usb1 6
    variable Usb2 7
    variable Virtual 11
    variable Wired 4
    variable Wireless 5
}

#
# Enumerated type: NetConnection
#

namespace eval NetConnection {
    variable Broadcast 3
    variable Ethernet 2
    variable Modem 1
}

#
# Enumerated type: NetworkRecordingSource
#

namespace eval NetworkRecordingSource {
    variable LocalPC 2
    variable LocalTCD 1
    variable RemoteServer 3
}

#
# Enumerated type: NowShowingSortOrder
#

namespace eval NowShowingSortOrder {
    variable Classic 0
    variable Clips 4
    variable Expiration 1
    variable PriorityObsolete 3
    variable Title 2
}

#
# Enumerated type: OutageReason
#

namespace eval OutageReason {
    variable PowerFailure 1
    variable SignalLoss 2
}

#
# Enumerated type: Palette
#

namespace eval Palette {
    variable Standard 1
    variable StandardUI 2
    variable StandardUI24bit 3
}

#
# Enumerated type: PartialRecordingPolicy
#

namespace eval PartialRecordingPolicy {
    variable NoPartials 0
    variable UpToFiveMinuteLoss 1
}

#
# Enumerated type: PatchLoadFrequency
#

namespace eval PatchLoadFrequency {
    variable Call 3
    variable Reboot 1
    variable Reset 2
    variable Unknown 0
}

#
# Enumerated type: PatchType
#

namespace eval PatchType {
    variable AT 2
    variable SRec 1
    variable Unknown 0
}

#
# Enumerated type: PrefsType
#

namespace eval PrefsType {
    variable Actor 17
    variable Advisory 6
    variable Country 3
    variable Director 19
    variable ExecProducer 20
    variable Genre 14
    variable GuestStar 18
    variable Host 23
    variable Last 24
    variable MpaaRating 2
    variable NetworkSource 4
    variable OldActor 7
    variable OldDirector 9
    variable OldExecProducer 10
    variable OldGuestStar 8
    variable OldHost 13
    variable OldProducer 11
    variable OldWriter 12
    variable Producer 21
    variable Program 16
    variable Series 15
    variable ShowType 1
    variable SourceType 5
    variable Writer 22
}

#
# Enumerated type: Premiere
#

namespace eval Premiere {
    variable Premiere 3
    variable SeasonFinale 1
    variable SeasonPremiere 4
    variable SeriesFinale 2
    variable SeriesPremiere 5
}

#
# Enumerated type: PresentationBehavior
#

namespace eval PresentationBehavior {
    variable AstroSeasonPass 9
    variable AstroSingleExplicit 10
    variable AutoRecordShowcase 15
    variable AutoRecordVideoStore 16
    variable CacheHistory 11
    variable Fuzzy 6
    variable Invisible 8
    variable LineIn 14
    variable RepeatManual 13
    variable SeasonPass 2
    variable SingleExplicit 1
    variable SingleManual 12
    variable SpeculativePayPerView 18
    variable TivoClips 5
    variable TivoClipsFuzzy 7
    variable TrioPass 17
    variable WatchOnly 4
    variable Wishlist 3
}

#
# Enumerated type: PresentationFeature
#

namespace eval PresentationFeature {
    variable KidsZoneBlackListed 2
    variable KidsZoneWhiteListed 1
}

#
# Enumerated type: ProgramGuideBehavior
#

namespace eval ProgramGuideBehavior {
    variable EveryEpisodeSeasonPass 7
    variable Manual 3
    variable NamedManual 8
    variable NotApplicable 6
    variable SeasonPass 2
    variable Service 5
    variable SingleExplicit 1
    variable WatchOnly 4
}

#
# Enumerated type: ProgramGuideSource
#

namespace eval ProgramGuideSource {
    variable Apg 2
    variable Tivo 1
}

#
# Enumerated type: ProgramSourceKidZone
#

namespace eval ProgramSourceKidZone {
    variable BlackListed 2
    variable NotListed 3
    variable WhiteListed 1
}

#
# Enumerated type: ProgressiveOutput
#

namespace eval ProgressiveOutput {
    variable Interlaced 1
    variable Progressive 2
    variable ProgressiveShrink 3
}

#
# Enumerated type: ProgressiveVideoFormat
#

namespace eval ProgressiveVideoFormat {
    variable Auto 1
    variable Film 2
    variable Video 3
}

#
# Enumerated type: RecordQuality
#

namespace eval RecordQuality {
    variable Best 100
    variable Good 0
    variable High 75
    variable Medium 40
    variable Unspecified -1
}

#
# Enumerated type: RecordingCreator
#

namespace eval RecordingCreator {
    variable Factory 4
    variable Influx 7
    variable Prioritizer 3
    variable RecordingQueue 5
    variable Service 2
    variable TemporaryRecording 6
    variable Viewer 1
}

#
# Enumerated type: RecordingDrmSignatureType
#

namespace eval RecordingDrmSignatureType {
    variable None 0
    variable Sig1 1
}

#
# Enumerated type: RecordingPartDrmSignatureType
#

namespace eval RecordingPartDrmSignatureType {
    variable None 0
    variable Sig1 1
}

#
# Enumerated type: RecordingQueueKeepAtLeast
#

namespace eval RecordingQueueKeepAtLeast {
    variable SpaceNeeded 1
    variable SpecifiedSeconds 3
    variable UserDeletes 2
}

#
# Enumerated type: RecordingState
#

namespace eval RecordingState {
    variable Allocated 7
    variable Cancelled 2
    variable Complete 4
    variable Deleted 5
    variable InProgress 3
    variable Pending 1
    variable Proposed 9
    variable Scheduled 6
    variable ServiceCancelled 8
}

#
# Enumerated type: RecordingUser
#

namespace eval RecordingUser {
    variable Blizzard 3
    variable DemoMode 6
    variable DtvDfb 8
    variable DtvSwUpdate 7
    variable PlanY 2
    variable ReplaceableBackground 5
    variable TivoClip 4
    variable Viewer 1
}

#
# Enumerated type: Role
#

namespace eval Role {
    variable Actor 8
    variable Choreographer 14
    variable Director 9
    variable ExecProducer 10
    variable Host 13
    variable OldActor 1
    variable OldChoreographer 7
    variable OldDirector 2
    variable OldExecProducer 3
    variable OldHost 6
    variable OldProducer 4
    variable OldWriter 5
    variable Producer 11
    variable Writer 12
}

#
# Enumerated type: SatConnectionType
#

namespace eval SatConnectionType {
    variable Auto 4
    variable DirectLNB 2
    variable SWM 3
    variable SimpleControl 1
    variable SimpleDiSEqC 0
}

#
# Enumerated type: SatDishType
#

namespace eval SatDishType {
    variable Additional72_5 6
    variable Additional95 7
    variable Dual 2
    variable Single 1
    variable Slimline3 4
    variable Slimline5 5
    variable Triple 3
}

#
# Enumerated type: ScartAuxInput
#

namespace eval ScartAuxInput {
    variable Pal 1
    variable Rgb 2
}

#
# Enumerated type: ScartTvOutput
#

namespace eval ScartTvOutput {
    variable PalOnly 1
    variable RgbPal 2
}

#
# Enumerated type: SeasonPassType
#

namespace eval SeasonPassType {
    variable CaptureRequest 5
    variable DailyData 6
    variable DtvDfb 13
    variable DtvSwUpdate 12
    variable Epg 8
    variable Fuzzy 4
    variable GenreTimerange 10
    variable InternetSeriesStation 11
    variable Keyword 3
    variable Manual 2
    variable NotScheduled 17
    variable RemoteRequest 16
    variable SeriesStation 1
    variable Showcase 14
    variable SingleExplicit 18
    variable SmartManual 9
    variable Time 7
    variable TrioUnknownSubscription 15
}

#
# Enumerated type: ServiceClass
#

namespace eval ServiceClass {
    variable Invalid 0
    variable Oxygen 2
    variable Standard 1
}

#
# Enumerated type: ServiceInterfaceType
#

namespace eval ServiceInterfaceType {
    variable NativeModem 1
    variable NetworkServiceAny 2
    variable Unknown 0
}

#
# Enumerated type: ServiceRecordingPriority
#

namespace eval ServiceRecordingPriority {
    variable High 3
    variable Normal 2
    variable NotServiceRecording 1
    variable Reserved1 4
    variable Reserved2 5
}

#
# Enumerated type: ServiceState
#

namespace eval ServiceState {
    variable CAPDeactivated 13
    variable Closed 8
    variable Deactivated 10
    variable Evaluation 11
    variable Good 3
    variable Lifetime 5
    variable NeverSetUp 7
    variable New 1
    variable NotSetUp 2
    variable OxygenFT 18
    variable OxygenFTNP 19
    variable OxygenFTP 17
    variable PastDue 6
    variable PastDueClosed 14
    variable Promotional 15
    variable PromotionalExpired 16
    variable Stolen 9
    variable Storefront 12
    variable Test 4
    variable Unknown 0
}

#
# Enumerated type: ServiceTier
#

namespace eval ServiceTier {
    variable Basic 1
    variable ExtendedBasic 2
    variable Music 5
    variable PayPerView 4
    variable Premium 3
    variable Unknown 0
}

#
# Enumerated type: SetupComplete
#

namespace eval SetupComplete {
    variable AllComplete 1
    variable DoNotUseThisBit 8
    variable GuidedSetupComplete 2
    variable None 0
    variable PhoneSetupComplete 4
}

#
# Enumerated type: ShowStatus
#

namespace eval ShowStatus {
    variable EveryEpisode 2
    variable FirstRunOnly 1
    variable RerunsAllowed 0
}

#
# Enumerated type: ShowType
#

namespace eval ShowType {
    variable LimitedSeries 4
    variable Miniseries 6
    variable PaidProgramming 7
    variable Serial 1
    variable Series 5
    variable ShortFilm 2
    variable Special 3
}

#
# Enumerated type: ShowcaseArea
#

namespace eval ShowcaseArea {
    variable ShowcaseArea1 1
    variable ShowcaseArea2 2
    variable TivolutionMagazine 0
}

#
# Enumerated type: ShowcaseAutoRecordOptions
#

namespace eval ShowcaseAutoRecordOptions {
    variable BrandedDtv 128
    variable DefaultHighSeasonPassPriority 8
    variable DefaultKeepUntilDelete 16
    variable DisplayAsMenuItem 1
    variable DisplayAsOptionPill 2
    variable DisplayPadding 32
    variable IsPPV 4
    variable OrderedShowings 64
}

#
# Enumerated type: ShowingBit
#

namespace eval ShowingBit {
    variable Blackout 64
    variable CableInTheClassroom 16
    variable CloseCaption 1
    variable DialogRating 524288
    variable Dvs 8192
    variable FvRating 1048576
    variable Hdtv 4096
    variable Intercast 128
    variable JoinedInProgress 8
    variable LanguageRating 262144
    variable Letterbox 1024
    variable Repeat 512
    variable Sap 32
    variable SexRating 65536
    variable Stereo 2
    variable Subtitle 4
    variable Subtitled 2048
    variable ThreeD 256
    variable ViolenceRating 131072
}

#
# Enumerated type: ShowingReason
#

namespace eval ShowingReason {
    variable Copy 2
    variable Manual 4
    variable NoPGDAvailable 5
    variable ProgramGuide 1
    variable Viewer 3
}

#
# Enumerated type: Signal
#

namespace eval Signal {
    variable Analog 2
    variable Digital 1
}

#
# Enumerated type: SignalType
#

namespace eval SignalType {
    variable ATSC 4
    variable ATSCBox 10
    variable Cable 2
    variable CableBox 5
    variable DBS 3
    variable DVBT 9
    variable DigitalCable 8
    variable DirecTV 6
    variable LineInput 7
    variable Rooftop 1
    variable Unknown 0
}

#
# Enumerated type: SingleExplicitFlag
#

namespace eval SingleExplicitFlag {
    variable Cds 10
    variable DelayedStart 2
    variable KeepForever 8
    variable KeepLonger 7
    variable LineIn 3
    variable LowPriority 6
    variable Manual 4
    variable NamedManual 5
    variable Network 9
    variable PayPerView 1
}

#
# Enumerated type: Size
#

namespace eval Size {
    variable ListItem 2
    variable Standard 1
}

#
# Enumerated type: SoundFormat
#

namespace eval SoundFormat {
    variable PCM 1
}

#
# Enumerated type: SoundVolume
#

namespace eval SoundVolume {
    variable Loud 4
    variable Medium 3
    variable Silent 1
    variable Soft 2
}

#
# Enumerated type: SourceType
#

namespace eval SourceType {
    variable Block 4
    variable Local 3
    variable Network 1
    variable Syndicated 2
}

#
# Enumerated type: SpigotServiceId
#

namespace eval SpigotServiceId {
    variable appact 2
    variable dtvfam 6
    variable groupdirectv 9
    variable groupdirectvelected 10
    variable grouptivo 7
    variable grouptivoelected 8
    variable mrv 5
    variable musicphoto 4
    variable testmap 1
    variable testmapb 13
    variable tivodct 12
    variable tivoext 14
    variable tivoffm 11
    variable tivopvr 3
}

#
# Enumerated type: Star
#

namespace eval Star {
    variable Four 7
    variable One 1
    variable OnePointFive 2
    variable Three 5
    variable ThreePointFive 6
    variable Two 3
    variable TwoPointFive 4
}

#
# Enumerated type: SubscriptionUIType
#

namespace eval SubscriptionUIType {
    variable CDS 1
}

#
# Enumerated type: Suggestions
#

namespace eval Suggestions {
    variable DisableAutoRecord 1
    variable RecordIfSpaceAvailable 0
    variable RecordOverExpiredPrograms 2
}

#
# Enumerated type: TagTargetActionType
#

namespace eval TagTargetActionType {
    variable BillboardId 4097
    variable HwwId 4
    variable ShowcaseId 2
    variable TivoClipId 3
    variable TmsId 1
    variable UnknownId 0
}

#
# Enumerated type: TapeStatus
#

namespace eval TapeStatus {
    variable MacrovisionEncoded 2
    variable PayToTapeNotPurchased 3
    variable TapingAllowed 1
}

#
# Enumerated type: TcpRemoteControlState
#

namespace eval TcpRemoteControlState {
    variable Disabled 1
    variable Enabled 2
}

#
# Enumerated type: ThemeOp
#

namespace eval ThemeOp {
    variable Not 3
    variable Optional 2
    variable Required 1
}

#
# Enumerated type: ThemeType
#

namespace eval ThemeType {
    variable Actor 2
    variable Advanced 4
    variable Compound 7
    variable Director 3
    variable Genre 5
    variable Keyword 1
    variable Title 6
}

#
# Enumerated type: TimeZone
#

namespace eval TimeZone {
    variable Alaska 5
    variable Central 2
    variable Eastern 1
    variable Gmt 7
    variable GmtMinus1 20
    variable GmtMinus11 24
    variable GmtMinus12 25
    variable GmtMinus2 21
    variable GmtMinus3 22
    variable GmtMinus4 23
    variable GmtPlus1 8
    variable GmtPlus10 17
    variable GmtPlus11 18
    variable GmtPlus12 19
    variable GmtPlus2 9
    variable GmtPlus3 10
    variable GmtPlus4 11
    variable GmtPlus5 12
    variable GmtPlus6 13
    variable GmtPlus7 14
    variable GmtPlus8 15
    variable GmtPlus9 16
    variable Hawaii 6
    variable Mountain 3
    variable Pacific 4
}

#
# Enumerated type: TmpStorageState
#

namespace eval TmpStorageState {
    variable Closed 1
    variable Opened 2
}

#
# Enumerated type: TuikResourceStateStatus
#

namespace eval TuikResourceStateStatus {
    variable Active 2
    variable Pending 1
}

#
# Enumerated type: TunerBehavior
#

namespace eval TunerBehavior {
    variable CacheHistory 10
    variable Cds 22
    variable DataBlizzard 9
    variable DataDtvDfbMandatory 18
    variable DataDtvDfbOptionalHigh 20
    variable DataDtvDfbOptionalLow 19
    variable DataDtvSwUpdateMandatory 15
    variable DataDtvSwUpdateOptional 16
    variable DataPlanY 5
    variable DelayedStart 17
    variable Epg 12
    variable Fuzzy 7
    variable IndefiniteLength 11
    variable LowSingleExplicit 14
    variable Network 21
    variable NotApplicable 8
    variable PayPerView 3
    variable SeasonPass 2
    variable SingleExplicit 1
    variable SpeculativePayPerView 23
    variable Time 13
    variable TivoClips 6
    variable WatchOnly 4
}

#
# Enumerated type: TvRating
#

namespace eval TvRating {
    variable 14 5
    variable AO 14
    variable AV 11
    variable C 9
    variable G 3
    variable M 6
    variable MA 10
    variable Nr 7
    variable P 8
    variable PGR 13
    variable Pg 4
    variable R 12
    variable Unknown 0
    variable Y 2
    variable Y7 1
}

#
# Enumerated type: UnionTagBehaviorType
#

namespace eval UnionTagBehaviorType {
    variable NoAttractionSound 16
    variable NotActionable 32
    variable RequireAdContentSet 1
    variable RequireBrandedSet 2
    variable ReturnToTagBeginning 4
    variable ReturnToTagEnd 8
}

#
# Enumerated type: UnionTagDetectionMethod
#

namespace eval UnionTagDetectionMethod {
    variable Ib 1
    variable Oob 2
    variable Vf 3
}

#
# Enumerated type: UnionTagType
#

namespace eval UnionTagType {
    variable Brandable 1
    variable IPreview4 2
    variable Unknown 0
}

#
# Enumerated type: ViewerEventAction
#

namespace eval ViewerEventAction {
    variable FastForward 5
    variable Off 2
    variable On 1
    variable Pause 4
    variable Play 3
    variable Rewind 6
    variable Tivo 7
}

#
# Enumerated type: ViewerSelectionType
#

namespace eval ViewerSelectionType {
    variable Bookmarked 8
    variable CaptureRequest 16
    variable Channel 4
    variable DailyData 17
    variable ExplicitTimer 5
    variable Extended 14
    variable FuzzyPackage 7
    variable FuzzyShow 6
    variable Guide 11
    variable IPreview 12
    variable ManualExtended 15
    variable ManualSeasonPass 10
    variable Name 3
    variable PackageRecommendation 2
    variable RemoteRecording 18
    variable SeasonPass 9
    variable ShowRecommendation 1
    variable WishListPass 13
}

#
# Enumerated type: WideScreenFormat
#

namespace eval WideScreenFormat {
    variable Letterbox 1
    variable PanAndScan 2
}

#
# Enumerated type: WienerDisplay
#

namespace eval WienerDisplay {
    variable Normal 0
    variable Shrink 1
}

#
# Enumerated type: ZapRequest
#

namespace eval ZapRequest {
    variable AlmostFactoryReset 4
    variable ClearPgdEtc 2
    variable FactoryReset 1
    variable None 0
    variable Prefs 3
}

#
# Enumerated bitfield type : PersistentBackdoor
#

namespace eval PersistentBackdoor {
    variable ThirtySecondSkip 0
}

#
# Enumerated bitfield type : SetupConfigured
#

namespace eval SetupConfigured {
    variable GuidedSetup 0
    variable NetworkSetup 2
    variable PhoneSetup 1
}

#
# Enumerated bitfield type : SignalSourceTemporary
#

namespace eval SignalSourceTemporary {
    variable IrCode 2
    variable Lineup 1
    variable Provider 0
}


